apiVersion: v1
kind: Service
metadata:
  name: gitops-service
spec:
  type: {{ .Values.service_type }}
prots:
- name: {{ .Chart.Name }}
  protocol: TCP
  port: 80
  targetPort: 8080
selector:
  app: {{ .Values.label }}
